using System.Text.Json.Serialization;
using MCP.EasyVerein.Domain.Converters;
using MCP.EasyVerein.Domain.Interfaces;
using MCP.EasyVerein.Domain.ValueObjects;

namespace MCP.EasyVerein.Domain.Entities;

/// <summary>
/// Represents the lending of an inventory object to a borrower in the easyVerein API.
/// </summary>
public class Lending : IHasId
{
    /// <summary>Gets or sets the unique identifier. Maps to API field '<c>id</c>'.</summary>
    [JsonPropertyName(LendingFields.Id)]
    public long Id { get; set; }

    /// <summary>Gets or sets the owning organization URL reference (read-only). Maps to API field '<c>org</c>'.</summary>
    [JsonPropertyName(LendingFields.Org)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Org { get; set; }

    /// <summary>Gets or sets the ID of the lent inventory object. Maps to API field '<c>parentInventoryObject</c>'.</summary>
    [JsonPropertyName(LendingFields.ParentInventoryObject)]
    [JsonConverter(typeof(FlexibleIdConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? ParentInventoryObjectId { get; set; }

    /// <summary>Gets or sets the contact details ID of the borrower. Maps to API field '<c>borrowAddress</c>'.</summary>
    [JsonPropertyName(LendingFields.BorrowAddress)]
    [JsonConverter(typeof(FlexibleIdConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public long? BorrowAddressId { get; set; }

    /// <summary>Gets or sets the display name generated by the API (read-only). Maps to API field '<c>name</c>'.</summary>
    [JsonPropertyName(LendingFields.Name)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? Name { get; set; }

    /// <summary>Gets or sets the creation timestamp (read-only). Maps to API field '<c>created_at</c>'.</summary>
    [JsonPropertyName(LendingFields.CreatedAt)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? CreatedAt { get; set; }

    /// <summary>Gets or sets the last-update timestamp (read-only). Maps to API field '<c>updated_at</c>'.</summary>
    [JsonPropertyName(LendingFields.UpdatedAt)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? UpdatedAt { get; set; }

    /// <summary>Gets or sets the date the lending is removed from the wastebasket (read-only). Maps to API field '<c>_deleteAfterDate</c>'.</summary>
    [JsonPropertyName(LendingFields.DeleteAfterDate)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTimeOffset? DeleteAfterDate { get; set; }

    /// <summary>Gets or sets the name of the user who deleted the lending (read-only). Maps to API field '<c>_deletedBy</c>'.</summary>
    [JsonPropertyName(LendingFields.DeletedBy)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? DeletedBy { get; set; }

    /// <summary>Gets or sets the date the object is lent out. Maps to API field '<c>borrowingDate</c>'.</summary>
    [JsonPropertyName(LendingFields.BorrowingDate)]
    [JsonConverter(typeof(DateOnlyJsonConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? BorrowingDate { get; set; }

    /// <summary>Gets or sets the date the object is returned. Maps to API field '<c>returnDate</c>'.</summary>
    [JsonPropertyName(LendingFields.ReturnDate)]
    [JsonConverter(typeof(DateOnlyJsonConverter))]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public DateTime? ReturnDate { get; set; }

    /// <summary>Gets or sets the number of lent pieces. Maps to API field '<c>quantity</c>'.</summary>
    [JsonPropertyName(LendingFields.Quantity)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public int? Quantity { get; set; }

    /// <summary>Gets or sets the time of day the object is lent out (HH:mm:ss). Maps to API field '<c>borrowTime</c>'.</summary>
    [JsonPropertyName(LendingFields.BorrowTime)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? BorrowTime { get; set; }

    /// <summary>Gets or sets the time of day the object is returned (HH:mm:ss). Maps to API field '<c>returnTime</c>'.</summary>
    [JsonPropertyName(LendingFields.ReturnTime)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? ReturnTime { get; set; }

    /// <summary>Gets or sets the lending state ('lent', 'inquiry' or 'returned'). Maps to API field '<c>state</c>'.</summary>
    [JsonPropertyName(LendingFields.State)]
    [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
    public string? State { get; set; }
}
