namespace MCP.EasyVerein.Domain.ValueObjects;

/// <summary>Constants for easyVerein lending API field names used in JSON serialization and query building.</summary>
internal static class LendingFields
{
    /// <summary>API field name for the unique lending identifier.</summary>
    internal const string Id = "id";

    /// <summary>API field name for the owning organization reference (read-only).</summary>
    internal const string Org = "org";

    /// <summary>API field name for the lent inventory object reference.</summary>
    internal const string ParentInventoryObject = "parentInventoryObject";

    /// <summary>API field name for the contact details reference of the borrower.</summary>
    internal const string BorrowAddress = "borrowAddress";

    /// <summary>API field name for the display name generated by the API (read-only).</summary>
    internal const string Name = "name";

    /// <summary>API field name for the creation timestamp (read-only).</summary>
    internal const string CreatedAt = "created_at";

    /// <summary>API field name for the last-update timestamp (read-only).</summary>
    internal const string UpdatedAt = "updated_at";

    /// <summary>API field name for the date the lending is removed from the wastebasket (read-only).</summary>
    internal const string DeleteAfterDate = "_deleteAfterDate";

    /// <summary>API field name for the name of the user who deleted the lending (read-only).</summary>
    internal const string DeletedBy = "_deletedBy";

    /// <summary>API field name for the date the object is lent out.</summary>
    internal const string BorrowingDate = "borrowingDate";

    /// <summary>API field name for the date the object is returned.</summary>
    internal const string ReturnDate = "returnDate";

    /// <summary>API field name for the number of lent pieces.</summary>
    internal const string Quantity = "quantity";

    /// <summary>API field name for the time of day the object is lent out.</summary>
    internal const string BorrowTime = "borrowTime";

    /// <summary>API field name for the time of day the object is returned.</summary>
    internal const string ReturnTime = "returnTime";

    /// <summary>API field name for the lending state ('lent', 'inquiry' or 'returned', max 50 characters).</summary>
    internal const string State = "state";

    /// <summary>API query parameter for filtering by a comma-separated list of IDs.</summary>
    internal const string IdIn = "id__in";

    /// <summary>API query parameter for filtering by a minimum borrowing date.</summary>
    internal const string BorrowingDateGte = "borrowingDate__gte";

    /// <summary>API query parameter for filtering by a maximum borrowing date.</summary>
    internal const string BorrowingDateLte = "borrowingDate__lte";

    /// <summary>API query parameter for filtering by a minimum return date.</summary>
    internal const string ReturnDateGte = "returnDate__gte";

    /// <summary>API query parameter for filtering by a maximum return date.</summary>
    internal const string ReturnDateLte = "returnDate__lte";

    /// <summary>API query parameter for filtering by a minimum quantity (exclusive).</summary>
    internal const string QuantityGt = "quantity__gt";

    /// <summary>API query parameter for filtering by a maximum quantity (exclusive).</summary>
    internal const string QuantityLt = "quantity__lt";

    /// <summary>API query parameter for excluding a lending state.</summary>
    internal const string StateNot = "state__ne";

    /// <summary>API query parameter for excluding an inventory object.</summary>
    internal const string ParentInventoryObjectNot = "parentInventoryObject__not";

    /// <summary>API query parameter for filtering by the borrowing member.</summary>
    internal const string BorrowMember = "borrowMember";

    /// <summary>API query parameter for excluding a borrowing member.</summary>
    internal const string BorrowMemberNot = "borrowMember__not";

    /// <summary>API query parameter for excluding a borrower address.</summary>
    internal const string BorrowAddressNot = "borrowAddress__not";

    /// <summary>API query parameter that limits the result to lendings whose return date is in the future.</summary>
    internal const string FutureReturnDate = "futureReturnDate";

    /// <summary>API query parameter for filtering by soft-deleted state.</summary>
    internal const string Deleted = "deleted";

    /// <summary>API query parameter for ordering results.</summary>
    internal const string Ordering = "ordering";

    /// <summary>API query parameter for full-text search.</summary>
    internal const string Search = "search";
}
